version: '3.8'

services:
  db:
    image: postgres:16
    container_name: alcohol_bot_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: alcohol_bot_redis
    restart: always
    ports:
      - "6379:6379"
  app:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: >
      sh -c "
        npm run migrate-up &&
        npm run start
      "
    restart: unless-stopped

volumes:
  db_data: