name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: pkg
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Set IMAGE_TAG
        run: |
          IMAGE_TAG="${VERSION}-${COMMIT_HASH}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            jucollet/hey-bob
          tags: |
            ${{ env.VERSION }}
            ${{ env.IMAGE_TAG }}
            type=ref,event=branch
            type=ref,event=pr

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Checkout heybob-deploy repo
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          repository: jucollet/heybob-deploy
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: heybob-deploy

      - name: Update prod image version
        if: github.event_name != 'pull_request'
        run: |
          sed -i "s|newTag: .*|newTag: ${{ env.IMAGE_TAG }}|g" heybob-deploy/prod/kustomization.yaml
          cd heybob-deploy
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add prod/kustomization.yaml
          git commit -m "Update prod image to ${{ env.IMAGE_TAG }}"
          git push
